Update build-caddy-alpine.yml

diff --git a/.github/workflows/build-caddy-alpine.yml b/.github/workflows/build-caddy-alpine.yml
--- a/.github/workflows/build-caddy-alpine.yml
+++ b/.github/workflows/build-caddy-alpine.yml
@@ -1,4 +1,4 @@
-name: Build and Push Alpine Docker Image
+name: Build and Push Caddy-Alpine Image
 
 on:
   repository_dispatch:
@@ -46,39 +46,21 @@ jobs:
             echo "VERSION=${{ github.event.client_payload.latest_version }}" >> $GITHUB_ENV
           fi
 
-      - name: Build and push Docker image (alpine)
+      - name: Build and push Caddy image (Alpine)
         uses: docker/build-push-action@v5
         with:
           context: .
-          file: Dockerfile
+          file: Dockerfile-Alpine
           push: true
-          #platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le,linux/s390x
-          platforms: linux/amd64
+          platforms: linux/amd64,linux/arm64
           tags: |
-            ghcr.io/${{ github.repository_owner }}/caddy-cloudflare-alpine:${{ env.VERSION }}
-            ghcr.io/${{ github.repository_owner }}/caddy-cloudflare-alpine:latest
-            ghcr.io/${{ github.repository_owner }}/caddy-cloudflare:${{ env.VERSION }}-alpine
-            ghcr.io/${{ github.repository_owner }}/caddy-cloudflare:alpine
-            ${{ secrets.DOCKERHUB_USERNAME }}/caddy-cloudflare-alpine:${{ env.VERSION }}
-            ${{ secrets.DOCKERHUB_USERNAME }}/caddy-cloudflare-alpine:latest
-            ${{ secrets.DOCKERHUB_USERNAME }}/caddy-cloudflare:${{ env.VERSION }}-alpine
-            ${{ secrets.DOCKERHUB_USERNAME }}/caddy-cloudflare:alpine
+            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ env.VERSION }}
+            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
+            ${{ github.actor }}/${{ github.event.repository.name }}:${{ env.VERSION }}
+            ${{ github.actor }}/${{ github.event.repository.name }}:latest
 
-      - name: Clean up Docker images
-        run: |
-          docker rmi ghcr.io/${{ github.repository_owner }}/caddy-cloudflare-alpine:${{ env.VERSION }} || true
-          docker rmi ghcr.io/${{ github.repository_owner }}/caddy-cloudflare:${{ env.VERSION }}-alpine || true
-          docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/caddy-cloudflare-alpine:${{ env.VERSION }} || true
-          docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/caddy-cloudflare:${{ env.VERSION }}-alpine || true
-          docker builder prune --force
-
-      - name: Create GitHub Release
-        uses: actions/create-release@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          tag_name: ${{ env.VERSION }}-alpine
-          release_name: "Caddy Alpine Release ${{ env.VERSION }}-alpine"
-          body: "New Caddy release detected. See the full release notes [here](https://github.com/caddyserver/caddy/releases/tag/${{ env.VERSION }})."
-          draft: false
-          prerelease: false
+      #- name: Clean up Docker images
+      #  run: |
+      #    docker rmi ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ env.VERSION }} || true
+      #    docker rmi ${{ github.actor }}/${{ github.event.repository.name }}:${{ env.VERSION }} || true
+      #    docker builder prune --force
